name: ppidunia
description: PPI Dunia

publish_to: "none"

version: 1.1.0+2

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  awesome_dialog: ^3.0.2
  bottom_picker: ^2.0.1
  cached_network_image: ^3.2.0
  carousel_slider: ^4.2.1
  chewie: ^1.7.0
  delayed_display: ^2.0.0
  detectable_text_field: ^3.0.2
  device_info_plus: ^9.1.1
  device_preview: ^1.1.0
  dio: ^5.3.2
  equatable: ^2.0.5
  external_path: ^1.0.3
  filesize: ^2.0.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.8
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.5
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_local_notifications: ^16.3.0
  flutter_localizations:
    sdk: flutter
  flutter_mentions: ^2.0.1
  flutter_native_image: ^0.0.6+1
  flutter_otp_text_field: ^1.1.1
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.1.0
  flutter_switch: ^0.3.2
  full_screen_image: ^2.0.0
  gallery_saver: ^2.3.2
  geocoding: ^2.0.4
  geolocator: ^9.0.2
  get_it: ^7.6.0
  google_api_headers: ^1.3.0
  google_maps_flutter: ^2.2.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  hex: ^0.2.0
  http: ^0.13.5
  image_cropper: ^1.4.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  lecle_flutter_absolute_path: ^0.0.2
  linkfy_text: ^1.1.5
  loading:
    git: https://github.com/bradintheusa/loading
  localization: ^2.1.0
  lottie: ^2.7.0
  multi_image_picker_plus: ^0.0.3
  new_version_plus: ^0.0.1+4
  open_file: ^3.3.2
  open_filex: ^4.4.0
  package_info_plus: ^4.0.1
  path: ^1.8.3
  path_provider: ^2.0.15
  permission_handler: ^10.4.3
  photo_view: ^0.14.0
  provider: ^6.0.4
  rich_readmore: ^1.1.1
  shared_preferences: ^2.2.0
  shimmer: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^1.1.0
  sn_progress_dialog: ^1.0.8
  soundpool: ^2.3.0
  stop_watch_timer: ^3.0.0
  syncfusion_flutter_pdf: ^23.2.6
  timeago: ^3.3.0
  tuple: ^2.0.1
  url_launcher: ^6.1.6
  uuid: ^3.0.7
  video_compress: ^3.1.2
  video_player: ^2.8.1
  webview_flutter: ^3.0.4

dependency_overrides:
  wakelock_windows: any
  win32: any

#flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
#  remove_alpha_ios: true
#  image_path: "assets/images/logo/app-icon.jpg"
dev_dependencies:
  build_runner: ^2.4.4

  #D
  date_time_picker:
    git:
      url: https://github.com/DavidHDJ/date_time_picker.git
      ref: 2.1.1
  file_picker:
    git:
      url: https://github.com/melWiss/flutter_file_picker.git
  flutter_test:
    sdk: flutter
  #  device_preview:
  #   git:
  #      url: https://github.com/bradrushworth/flutter_device_preview.git
  #      path: device_preview
  # Firebase
  # firebase_core_platform_interface: 5.0.0
  #H
  http_mock_adapter: ^0.4.4

  #M
  mockito: ^5.0.8

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/
    - assets/language/
    - assets/images/
    - assets/images/auth/
    - assets/images/default/
    - assets/images/icons/
    - assets/images/card/
    - assets/images/avatar/
    - assets/images/background/
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/lottie/

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/sf_pro/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/sf_pro/SFPRODISPLAYMEDIUM.OTF
        - asset: assets/fonts/sf_pro/SFPRODISPLAYBOLD.OTF
